name: Test

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Modified files
        run: |
          git diff --name-only --diff-filter=d master~ master
      - name: Deleted files
        run: |
          git diff --name-only --diff-filter=D master~ master
      - name: Added files
        run: |
          git diff --name-only --diff-filter=A master~ master
      - name: Renamed files
        run: |
          git diff --name-only --diff-filter=R master~ master
